ALTER TABLE contracts ADD COLUMN IF NOT EXISTS headcount INTEGER;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS amount_cents INTEGER;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS payment_intent_id VARCHAR(255);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS stripe_amount_total INTEGER;
